specific:
  sample_map: <path/to>/sample_map.tsv
  barcodes_dir: <path/to>/directory_containing_barcodes_to_celltype
  cupcake: <path/to>/scIsoPrep/scripts/SQANTI3-1.6/cDNA_Cupcake
  workdir: <path/to>/output_files
  maxmem: 16000 #maximum memory for collapsing, reduce


static:
  data_path: <path/to>/data_bamfiles
  bin_path: <path/to>/scIsoPrep/scripts
  adapters: lima_adapters2.fasta
  genome: <path/to>/hg38.fa
  annotation: <path/to>/gencode.vXX.annotation.gtf
